// Auto-generated by generateSilhouetteProfiles.cjs
// Do not edit manually unless intentional.
window.propertySilhouetteProfiles = 
{
  "@Solaris Business Hub": {
    "profile8": [
      0.923,
      1.137,
      1.189,
      1.243,
      1.214,
      1.167,
      1.128,
      1.073
    ],
    "bands": [
      1,
      0.649,
      0.521
    ],
    "confidence": 0.886,
    "dominantColor": "#a0a4a9",
    "image": "imagesss/Shilp-Business-Gateway-01.jpeg",
    "source": "image-local"
  },
  "@Sun Orbit": {
    "profile8": [
      0.861,
      1.201,
      1.247,
      1.284,
      1.224,
      1.215,
      1.132,
      0.948
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9c8377",
    "image": "imagesss/Sunflower-01.png",
    "source": "image-local"
  },
  "@WestBank": {
    "profile8": [
      0.902,
      1.06,
      1.113,
      1.232,
      1.301,
      1.262,
      1.193,
      1.137
    ],
    "bands": [
      1,
      0.824,
      0.568
    ],
    "confidence": 1,
    "dominantColor": "#8aa2be",
    "image": "imagesss/WestBank-1.jpg",
    "source": "image-local"
  },
  "@Shalin Square": {
    "profile8": [
      1.001,
      1.276,
      1.267,
      1.199,
      1.199,
      1.124,
      1.012,
      0.984
    ],
    "bands": [
      1,
      0.52,
      0.376
    ],
    "confidence": 1,
    "dominantColor": "#968f91",
    "image": "imagesss/Shalin-square-3.jpeg",
    "source": "image-local"
  },
  "@Sun Residency": {
    "profile8": [
      1.164,
      1.26,
      1.249,
      1.255,
      1.038,
      1.206,
      1.293,
      1.138
    ],
    "bands": [
      1,
      0.95,
      0.809
    ],
    "confidence": 0.891,
    "dominantColor": "#8a7d54",
    "image": "imagesss/Shilp-Residency-03.jpeg",
    "source": "image-local"
  },
  "@Sheladia Sarva": {
    "profile8": [
      1.005,
      1.014,
      1.18,
      1.127,
      1.081,
      1.06,
      1.027,
      0.933
    ],
    "bands": [
      1,
      0.782,
      0.673
    ],
    "confidence": 0.715,
    "dominantColor": "#8ea4ba",
    "image": "imagesss/Bopal-01.jpg",
    "source": "image-local"
  },
  "Limited Plots @Karnavati Club Road": {
    "profile8": [
      1.282,
      1.192,
      0.979,
      1.288,
      1.111,
      1.043,
      1.289,
      1.281
    ],
    "bands": [
      1,
      0.52,
      0.781
    ],
    "confidence": 0.604,
    "dominantColor": "#bbd25c",
    "image": "imagesss/Karnavati Club Road.png",
    "source": "image-local"
  },
  "@Anmol Ambience": {
    "profile8": [
      0.903,
      0.948,
      1.193,
      1.195,
      1.232,
      1.146,
      0.91,
      0.917
    ],
    "bands": [
      1,
      0.52,
      0.554
    ],
    "confidence": 1,
    "dominantColor": "#829fbb",
    "image": "imagesss/Anmol-Ambience.jpg",
    "source": "image-local"
  },
  "C.G. Road Showroom": {
    "profile8": [
      1.282,
      1.192,
      0.979,
      1.288,
      1.111,
      1.043,
      1.289,
      1.281
    ],
    "bands": [
      1,
      0.52,
      0.781
    ],
    "confidence": 0.604,
    "dominantColor": "#bbd25c",
    "image": "imagesss/Karnavati Club Road.png",
    "source": "image-local"
  },
  "Pre-Leased property 3rd, 5th, 6th Floor": {
    "profile8": [
      1.298,
      1.302,
      1.228,
      1.007,
      1.02,
      0.918,
      0.957,
      0.9
    ],
    "bands": [
      1,
      0.52,
      0.7
    ],
    "confidence": 1,
    "dominantColor": "#ccb9a9",
    "image": "imagesss/premier-01.png",
    "source": "image-local"
  },
  "@Arham Luxuria": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "@Aryan Elegance": {
    "profile8": [
      1.288,
      0.907,
      1.227,
      1.278,
      1.247,
      1.113,
      1.06,
      1.04
    ],
    "bands": [
      1,
      0.768,
      0.415
    ],
    "confidence": 1,
    "dominantColor": "#87a0ab",
    "image": "imagesss/Aryan-elegance-1.jpeg",
    "source": "image-local"
  },
  "@Siddharth Vrundavan": {
    "profile8": [
      0.984,
      1.113,
      1.22,
      1.24,
      1.156,
      1.226,
      1.094,
      1.096
    ],
    "bands": [
      1,
      0.794,
      0.587
    ],
    "confidence": 0.689,
    "dominantColor": "#6b7b84",
    "image": "imagesss/Siddharth-Gardenia-1.jpeg",
    "source": "image-local"
  },
  "@Siddharth Gardenia": {
    "profile8": [
      1.031,
      1.198,
      1.27,
      1.146,
      1.262,
      1.191,
      1.158,
      1.048
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#806d6c",
    "image": "imagesss/Siddharth-Heaven-01.jpg",
    "source": "image-local"
  },
  "Luxurious 3 BHK Flat": {
    "profile8": [
      0.969,
      1.006,
      1.147,
      1.147,
      1.095,
      1.071,
      1.099,
      1.019
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.314,
    "dominantColor": "#9baaa9",
    "image": "imagesss/Isometric flat 3d concept of business analysis financial report accounting statisticseting research data analysis _ Premium Vector.jpg.jpeg",
    "source": "image-local"
  },
  "@Eternity": {
    "profile8": [
      0.877,
      1.062,
      1.14,
      1.243,
      1.274,
      1.194,
      1.121,
      0.866
    ],
    "bands": [
      1,
      0.95,
      0.603
    ],
    "confidence": 1,
    "dominantColor": "#8797c6",
    "image": "imagesss/Eternity-03.jpeg",
    "source": "image-local"
  },
  "@Aavyan": {
    "profile8": [
      0.964,
      1.128,
      1.158,
      1.287,
      1.239,
      1.114,
      1.079,
      0.975
    ],
    "bands": [
      1,
      0.932,
      0.603
    ],
    "confidence": 1,
    "dominantColor": "#8f6e47",
    "image": "imagesss/Aavyan-02.jpg",
    "source": "image-local"
  },
  "@Kadamb": {
    "profile8": [
      1.297,
      1.302,
      1.121,
      1.246,
      1.216,
      1.296,
      1.278,
      1.017
    ],
    "bands": [
      1,
      0.69,
      0.704
    ],
    "confidence": 0.866,
    "dominantColor": "#977453",
    "image": "imagesss/Kadamb-02.png",
    "source": "image-local"
  },
  "@Sun Flower": {
    "profile8": [
      0.861,
      1.201,
      1.247,
      1.284,
      1.224,
      1.215,
      1.132,
      0.948
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9c8377",
    "image": "imagesss/Sunflower-01.png",
    "source": "image-local"
  },
  "@Malabar Retreat": {
    "profile8": [
      1.103,
      1.144,
      1.305,
      1.295,
      1.305,
      1.305,
      1.055,
      1.075
    ],
    "bands": [
      1,
      0.854,
      0.463
    ],
    "confidence": 1,
    "dominantColor": "#9c8780",
    "image": "imagesss/Malabar-Retreat-1.png",
    "source": "image-local"
  },
  "@The Imperial Heights": {
    "profile8": [
      0.927,
      1.099,
      1.147,
      1.214,
      1.225,
      1.237,
      1.111,
      0.943
    ],
    "bands": [
      1,
      0.938,
      0.469
    ],
    "confidence": 1,
    "dominantColor": "#b0999c",
    "image": "imagesss/Imperial-Heights-03.jpeg",
    "source": "image-local"
  },
  "@Satyam Apartment": {
    "profile8": [
      1.044,
      1.184,
      1.129,
      1.282,
      1.269,
      1.277,
      1.182,
      0.989
    ],
    "bands": [
      1,
      0.613,
      0.707
    ],
    "confidence": 1,
    "dominantColor": "#8b969f",
    "image": "imagesss/Satyam-01.png",
    "source": "image-local"
  },
  "@Obsidian Towers": {
    "profile8": [
      1,
      1.282,
      1.282,
      1.277,
      1.282,
      1.282,
      1.282,
      0.992
    ],
    "bands": [
      1,
      0.819,
      0.511
    ],
    "confidence": 1,
    "dominantColor": "#6f6e80",
    "image": "imagesss/Obisidian-2.png",
    "source": "image-local"
  },
  "@Parkview One": {
    "profile8": [
      0.945,
      1.082,
      1.191,
      1.301,
      1.271,
      0.934,
      0.945,
      0.945
    ],
    "bands": [
      1,
      0.52,
      0.402
    ],
    "confidence": 1,
    "dominantColor": "#8c8a97",
    "image": "imagesss/ParkView-one-02.jpeg",
    "source": "image-local"
  },
  "@Aster Neo": {
    "profile8": [
      0.978,
      1.114,
      1.16,
      1.063,
      1.117,
      1.079,
      1.056,
      1.273
    ],
    "bands": [
      1,
      0.744,
      0.451
    ],
    "confidence": 0.934,
    "dominantColor": "#b0968b",
    "image": "imagesss/Aster-Neo-2.png",
    "source": "image-local"
  },
  "@Embrace": {
    "profile8": [
      0.997,
      1.111,
      1.224,
      1.263,
      1.213,
      1.114,
      1.087,
      0.99
    ],
    "bands": [
      1,
      0.925,
      0.478
    ],
    "confidence": 0.91,
    "dominantColor": "#909fb0",
    "image": "imagesss/Embrace-the-wind-02.jpg",
    "source": "image-local"
  },
  "@Elysium Phase-2": {
    "profile8": [
      0.978,
      1.151,
      1.194,
      1.232,
      1.286,
      1.225,
      0.871,
      0.862
    ],
    "bands": [
      1,
      0.833,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#94a2b4",
    "image": "imagesss/vinayak-elysium-01.jpg",
    "source": "image-local"
  },
  "@Shivalik Green Field": {
    "profile8": [
      0.95,
      1.086,
      1.147,
      1.158,
      1.261,
      1.267,
      1.078,
      0.9
    ],
    "bands": [
      1,
      0.722,
      0.506
    ],
    "confidence": 1,
    "dominantColor": "#a39b9e",
    "image": "imagesss/Greenfield-01.jpeg",
    "source": "image-local"
  },
  "@Paarijat": {
    "profile8": [
      0.947,
      1.047,
      1.065,
      1.21,
      1.257,
      1.196,
      1.143,
      0.918
    ],
    "bands": [
      1,
      0.742,
      0.539
    ],
    "confidence": 1,
    "dominantColor": "#80828a",
    "image": "imagesss/Paarijat-02.jpeg",
    "source": "image-local"
  },
  "@Ambrosia": {
    "profile8": [
      1.158,
      1.192,
      1.111,
      1.098,
      1.103,
      1.073,
      1.277,
      1.279
    ],
    "bands": [
      1,
      0.917,
      0.281
    ],
    "confidence": 0.846,
    "dominantColor": "#896a44",
    "image": "imagesss/Embrosia-01.jpeg",
    "source": "image-local"
  },
  "@Shilp Skyline": {
    "profile8": [
      0.966,
      0.961,
      1.214,
      1.303,
      1.169,
      1.066,
      1.11,
      1.121
    ],
    "bands": [
      1,
      0.52,
      0.424
    ],
    "confidence": 1,
    "dominantColor": "#96948f",
    "image": "imagesss/Skyline-01.jpeg",
    "source": "image-local"
  },
  "@The West Park": {
    "profile8": [
      1.113,
      1.201,
      1.188,
      1.219,
      1.288,
      1.304,
      1.28,
      1.178
    ],
    "bands": [
      1,
      0.948,
      0.792
    ],
    "confidence": 0.844,
    "dominantColor": "#758446",
    "image": "imagesss/The-Westpark-01.jpeg",
    "source": "image-local"
  },
  "@The North Park": {
    "profile8": [
      1.113,
      1.201,
      1.188,
      1.219,
      1.288,
      1.304,
      1.28,
      1.178
    ],
    "bands": [
      1,
      0.948,
      0.792
    ],
    "confidence": 0.844,
    "dominantColor": "#758446",
    "image": "imagesss/The-Westpark-01.jpeg",
    "source": "image-local"
  },
  "@Belrosa": {
    "profile8": [
      0.9,
      1.048,
      1.2,
      1.253,
      1.298,
      0.894,
      0.947,
      1.098
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#8a8aa3",
    "image": "imagesss/Belrosa-02.jpeg",
    "source": "image-local"
  },
  "@Luxurious 3 BHK Flats Pre-Launch": {
    "profile8": [
      1.298,
      1.302,
      1.228,
      1.007,
      1.02,
      0.918,
      0.957,
      0.9
    ],
    "bands": [
      1,
      0.52,
      0.7
    ],
    "confidence": 1,
    "dominantColor": "#ccb9a9",
    "image": "imagesss/premier-01.png",
    "source": "image-local"
  },
  "@Shilp Residency": {
    "profile8": [
      1.164,
      1.26,
      1.249,
      1.255,
      1.038,
      1.206,
      1.293,
      1.138
    ],
    "bands": [
      1,
      0.95,
      0.809
    ],
    "confidence": 0.891,
    "dominantColor": "#8a7d54",
    "image": "imagesss/Shilp-Residency-03.jpeg",
    "source": "image-local"
  },
  "@Shilp Business Gateway": {
    "profile8": [
      0.923,
      1.137,
      1.189,
      1.243,
      1.214,
      1.167,
      1.128,
      1.073
    ],
    "bands": [
      1,
      0.649,
      0.521
    ],
    "confidence": 0.886,
    "dominantColor": "#a0a4a9",
    "image": "imagesss/Shilp-Business-Gateway-01.jpeg",
    "source": "image-local"
  },
  "@Shilp Celestial": {
    "profile8": [
      0.923,
      1.137,
      1.189,
      1.243,
      1.214,
      1.167,
      1.128,
      1.073
    ],
    "bands": [
      1,
      0.649,
      0.521
    ],
    "confidence": 0.886,
    "dominantColor": "#a0a4a9",
    "image": "imagesss/Shilp-Business-Gateway-01.jpeg",
    "source": "image-local"
  },
  "@Brij Sandalwood": {
    "profile8": [
      1.149,
      1.261,
      1.26,
      1.269,
      1.278,
      1.27,
      1.281,
      0.947
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#484537",
    "image": "imagesss/Sandlewood-02.jpg",
    "source": "image-local"
  },
  "@Brij IRIS": {
    "profile8": [
      0.917,
      0.907,
      1.298,
      1.278,
      1.271,
      1.271,
      1.207,
      0.972
    ],
    "bands": [
      1,
      0.621,
      0.609
    ],
    "confidence": 1,
    "dominantColor": "#9c9982",
    "image": "imagesss/IRIS-01.jpg",
    "source": "image-local"
  },
  "@Brij Azalea": {
    "profile8": [
      1.004,
      1.179,
      1.193,
      1.272,
      1.304,
      1.267,
      1.253,
      1.072
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#908997",
    "image": "imagesss/Azalea-02.jpg",
    "source": "image-local"
  },
  "@Siddharth Haven": {
    "profile8": [
      1.031,
      1.198,
      1.27,
      1.146,
      1.262,
      1.191,
      1.158,
      1.048
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#806d6c",
    "image": "imagesss/Siddharth-Heaven-01.jpg",
    "source": "image-local"
  },
  "@De Casa": {
    "profile8": [
      1.005,
      1.112,
      1.199,
      1.292,
      1.227,
      1.138,
      1.082,
      0.908
    ],
    "bands": [
      1,
      0.776,
      0.474
    ],
    "confidence": 1,
    "dominantColor": "#99a4b7",
    "image": "imagesss/De-casa-03.jpg",
    "source": "image-local"
  },
  "@Solaris Residency": {
    "profile8": [
      1.164,
      1.26,
      1.249,
      1.255,
      1.038,
      1.206,
      1.293,
      1.138
    ],
    "bands": [
      1,
      0.95,
      0.809
    ],
    "confidence": 0.891,
    "dominantColor": "#8a7d54",
    "image": "imagesss/Shilp-Residency-03.jpeg",
    "source": "image-local"
  },
  "@Suresha a New": {
    "profile8": [
      1.291,
      1.229,
      1.268,
      1.181,
      1.21,
      1.145,
      1.186,
      1.099
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.731,
    "dominantColor": "#74765b",
    "image": "imagesss/Solaris-Residency-01.jpg",
    "source": "image-local"
  },
  "@Rameshwar City": {
    "profile8": [
      0.977,
      1.204,
      1.228,
      1.228,
      1.209,
      1.168,
      1.141,
      1.141
    ],
    "bands": [
      1,
      0.614,
      0.739
    ],
    "confidence": 0.83,
    "dominantColor": "#b09a8a",
    "image": "imagesss/Ramershwarcity-01.jpeg",
    "source": "image-local"
  },
  "@Ganesh Luxuria": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "@Vikram Luxuria Living": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "@The Empiirean": {
    "profile8": [
      0.941,
      1.134,
      1.281,
      1.302,
      1.2,
      1.183,
      1.145,
      0.963
    ],
    "bands": [
      1,
      0.586,
      0.667
    ],
    "confidence": 1,
    "dominantColor": "#9c939a",
    "image": "imagesss/Empiirean-01.jpeg",
    "source": "image-local"
  },
  "@Sahashya Skyzenia": {
    "profile8": [
      1.105,
      0.941,
      1.288,
      1.29,
      1.211,
      1.249,
      1.151,
      1.046
    ],
    "bands": [
      1,
      0.8,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#596985",
    "image": "imagesss/Skyzenia-02.jpeg",
    "source": "image-local"
  },
  "@Brillia by Pravish": {
    "profile8": [
      0.999,
      0.984,
      1.285,
      1.217,
      0.999,
      0.979,
      0.974,
      0.985
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#b2b9b0",
    "image": "imagesss/Brillia-02.jpg",
    "source": "image-local"
  },
  "@Parkview Prism": {
    "profile8": [
      0.951,
      1.156,
      1.187,
      1.188,
      1.186,
      1.181,
      1.15,
      0.915
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 0.951,
    "dominantColor": "#b5aca5",
    "image": "imagesss/atham-prism-02.jpg",
    "source": "image-local"
  },
  "@Vivaan Ixora": {
    "profile8": [
      0.942,
      1.071,
      1.163,
      1.267,
      1.213,
      1.103,
      0.943,
      0.899
    ],
    "bands": [
      1,
      0.551,
      0.472
    ],
    "confidence": 1,
    "dominantColor": "#a6a4a0",
    "image": "imagesss/Vivaan-Ixora-02.jpeg",
    "source": "image-local"
  },
  "@Vivaan Essence": {
    "profile8": [
      1.013,
      1.242,
      1.29,
      1.214,
      1.134,
      1.061,
      1.045,
      0.89
    ],
    "bands": [
      1,
      0.95,
      0.573
    ],
    "confidence": 1,
    "dominantColor": "#8499b7",
    "image": "imagesss/Vivaan-Essence-01.jpeg",
    "source": "image-local"
  },
  "@Vivaan Solitaire": {
    "profile8": [
      0.86,
      0.877,
      1.256,
      1.191,
      1.223,
      0.946,
      0.874,
      0.867
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#a4aad4",
    "image": "imagesss/Vivaan-Solitaire-01.jpeg",
    "source": "image-local"
  },
  "@Vivaan Aura": {
    "profile8": [
      0.961,
      1.099,
      1.188,
      1.258,
      1.286,
      1.198,
      0.952,
      0.968
    ],
    "bands": [
      1,
      0.583,
      0.594
    ],
    "confidence": 1,
    "dominantColor": "#a89d97",
    "image": "imagesss/Vivaan-Aura-01.jpeg",
    "source": "image-local"
  },
  "@Vivaan Oliver": {
    "profile8": [
      0.948,
      1.216,
      1.203,
      1.272,
      1.243,
      1.18,
      1.141,
      0.986
    ],
    "bands": [
      1,
      0.869,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#af979b",
    "image": "imagesss/Vivaan-Oliver-01.jpeg",
    "source": "image-local"
  },
  "@Vivaan Orbit": {
    "profile8": [
      0.994,
      1.199,
      1.208,
      1.263,
      1.272,
      1.266,
      1.27,
      1.265
    ],
    "bands": [
      1,
      0.876,
      0.82
    ],
    "confidence": 0.928,
    "dominantColor": "#af9869",
    "image": "imagesss/Sun-orbit-1.jpg",
    "source": "image-local"
  },
  "@THE ORION": {
    "profile8": [
      0.915,
      0.921,
      1.218,
      1.218,
      1.223,
      1.271,
      0.927,
      0.986
    ],
    "bands": [
      1,
      0.52,
      0.33
    ],
    "confidence": 1,
    "dominantColor": "#a3aec3",
    "image": "imagesss/Orion-01.jpeg",
    "source": "image-local"
  },
  "@Aryajeet Surya": {
    "profile8": [
      1.151,
      0.975,
      1.203,
      1.241,
      1.253,
      1.251,
      1.04,
      1.081
    ],
    "bands": [
      1,
      0.66,
      0.532
    ],
    "confidence": 0.882,
    "dominantColor": "#76726f",
    "image": "imagesss/suryam-03.jpg",
    "source": "image-local"
  },
  "@Aarya Edge": {
    "profile8": [
      1.081,
      1.294,
      1.293,
      1.298,
      1.299,
      1.299,
      1.299,
      0.961
    ],
    "bands": [
      1,
      0.535,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#969da8",
    "image": "imagesss/Arya-edge-01.jpg",
    "source": "image-local"
  },
  "@Nandita Sampann": {
    "profile8": [
      0.944,
      0.963,
      1.163,
      1.206,
      1.236,
      1.185,
      0.95,
      0.936
    ],
    "bands": [
      1,
      0.52,
      0.417
    ],
    "confidence": 1,
    "dominantColor": "#8e979e",
    "image": "imagesss/Nandita-02.jpeg",
    "source": "image-local"
  },
  "@La Gracia": {
    "profile8": [
      1.305,
      1.299,
      1.275,
      1.004,
      1.24,
      1.292,
      1.298,
      1.05
    ],
    "bands": [
      1,
      0.52,
      0.319
    ],
    "confidence": 0.636,
    "dominantColor": "#97a4ac",
    "image": "imagesss/La-Gracia-01.jpeg",
    "source": "image-local"
  },
  "@Olive Greens": {
    "profile8": [
      0.932,
      0.912,
      1.242,
      1.266,
      1.102,
      1.107,
      1.28,
      1.282
    ],
    "bands": [
      1,
      0.52,
      0.298
    ],
    "confidence": 1,
    "dominantColor": "#a19ead",
    "image": "imagesss/Olive-Greens-02.jpeg",
    "source": "image-local"
  },
  "@Aarya Epoch": {
    "profile8": [
      0.969,
      1.148,
      1.218,
      1.23,
      1.229,
      0.956,
      1.264,
      1.191
    ],
    "bands": [
      1,
      0.659,
      0.747
    ],
    "confidence": 1,
    "dominantColor": "#b7875a",
    "image": "imagesss/Arya-Epoch-03.jpeg",
    "source": "image-local"
  },
  "@Rajshree Regalia": {
    "profile8": [
      1.124,
      1.121,
      1.177,
      1.005,
      1.284,
      1.011,
      0.987,
      1.207
    ],
    "bands": [
      1,
      0.52,
      0.366
    ],
    "confidence": 0.809,
    "dominantColor": "#a99a87",
    "image": "imagesss/REGALIA-01.jpg",
    "source": "image-local"
  },
  "@Bluebell": {
    "profile8": [
      1.114,
      1.183,
      1.284,
      1.297,
      1.265,
      1.222,
      1.204,
      1.12
    ],
    "bands": [
      1,
      0.828,
      0.82
    ],
    "confidence": 0.87,
    "dominantColor": "#6f7677",
    "image": "imagesss/Bluebell-02.jpg",
    "source": "image-local"
  },
  "@Adani Archway": {
    "profile8": [
      0.887,
      1.062,
      1.063,
      1.1,
      1.172,
      1.219,
      1.207,
      1.255
    ],
    "bands": [
      1,
      0.886,
      0.543
    ],
    "confidence": 1,
    "dominantColor": "#5e7daa",
    "image": "imagesss/Archway-02.jpg",
    "source": "image-local"
  },
  "@Adani Augusta": {
    "profile8": [
      0.91,
      1.014,
      1.079,
      1.129,
      1.024,
      1.278,
      1.256,
      1.295
    ],
    "bands": [
      1,
      0.714,
      0.532
    ],
    "confidence": 1,
    "dominantColor": "#c1b1b8",
    "image": "imagesss/Agusta-01.jpg",
    "source": "image-local"
  },
  "@Adani Atrius": {
    "profile8": [
      1.124,
      1.055,
      0.971,
      1.014,
      0.971,
      1.055,
      1.037,
      1.297
    ],
    "bands": [
      1,
      0.531,
      0.358
    ],
    "confidence": 0.99,
    "dominantColor": "#b7aea5",
    "image": "imagesss/Artius-01.jpg",
    "source": "image-local"
  },
  "@Shankus Aatmantan": {
    "profile8": [
      1.266,
      1.27,
      1.172,
      1.225,
      1.274,
      1.199,
      1.22,
      1.249
    ],
    "bands": [
      1,
      0.69,
      0.762
    ],
    "confidence": 0.621,
    "dominantColor": "#878f96",
    "image": "imagesss/AATMANTAN-04.png",
    "source": "image-local"
  },
  "@Elysia by Sobha": {
    "profile8": [
      0.877,
      1.211,
      1.176,
      1.172,
      1.14,
      1.23,
      1.077,
      0.866
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9b979c",
    "image": "imagesss/Elysia-02.jpg",
    "source": "image-local"
  },
  "@The Taurus": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Shankus Opus": {
    "profile8": [
      1.246,
      1.289,
      1.28,
      1.242,
      1.26,
      1.282,
      1.299,
      1.283
    ],
    "bands": [
      1,
      0.52,
      0.614
    ],
    "confidence": 0.314,
    "dominantColor": "#9e93ad",
    "image": "imagesss/AATMANTAN-02.jpg",
    "source": "image-local"
  },
  "@Meghalaya by Rajyash": {
    "profile8": [
      0.906,
      0.914,
      1.146,
      1.211,
      1.242,
      1.285,
      1.18,
      1.135
    ],
    "bands": [
      1,
      0.762,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#5c6277",
    "image": "imagesss/Meghalaya-03.jpg",
    "source": "image-local"
  },
  "@Divya Heights": {
    "profile8": [
      0.927,
      1.099,
      1.147,
      1.214,
      1.225,
      1.237,
      1.111,
      0.943
    ],
    "bands": [
      1,
      0.938,
      0.469
    ],
    "confidence": 1,
    "dominantColor": "#b0999c",
    "image": "imagesss/Imperial-Heights-03.jpeg",
    "source": "image-local"
  },
  "@Dharohar": {
    "profile8": [
      1.063,
      1.234,
      1.247,
      1.189,
      1.245,
      1.2,
      1.185,
      1.205
    ],
    "bands": [
      1,
      0.594,
      0.417
    ],
    "confidence": 0.685,
    "dominantColor": "#9c857d",
    "image": "imagesss/web-fallback/dharohar-web-3.jpeg",
    "source": "image-web-fallback"
  },
  "@The Nest": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Artham 97": {
    "profile8": [
      1.27,
      1.298,
      1.249,
      1.243,
      1.233,
      1.119,
      1.123,
      0.994
    ],
    "bands": [
      1,
      0.648,
      0.495
    ],
    "confidence": 0.953,
    "dominantColor": "#8c9da0",
    "image": "imagesss/Artham-97.jpeg",
    "source": "image-local"
  },
  "@Sakar Sky": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "@Super Shaligram": {
    "profile8": [
      1.253,
      1.292,
      1.248,
      1.198,
      1.244,
      1.253,
      1.188,
      1.202
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.705,
    "dominantColor": "#72696d",
    "image": "imagesss/Super-Shaligram-01.jpg",
    "source": "image-local"
  },
  "@Evana by Shashwat": {
    "profile8": [
      1.293,
      1.286,
      1.218,
      1.292,
      1.3,
      1.083,
      0.868,
      1.305
    ],
    "bands": [
      1,
      0.611,
      0.639
    ],
    "confidence": 1,
    "dominantColor": "#a09a8c",
    "image": "imagesss/Evana-01.jpg",
    "source": "image-local"
  },
  "@Shivanjali by Shashwat": {
    "profile8": [
      0.937,
      1.212,
      1.212,
      1.212,
      1.212,
      1.212,
      1.212,
      1.038
    ],
    "bands": [
      1,
      0.897,
      0.69
    ],
    "confidence": 0.928,
    "dominantColor": "#a8a197",
    "image": "imagesss/Shivanjali-01.jpg",
    "source": "image-local"
  },
  "@Embrace The Wind": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@The Gate by Dev Aashish": {
    "profile8": [
      1.29,
      0.933,
      1.299,
      1.245,
      1.259,
      1.296,
      0.983,
      0.939
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#8ba0a8",
    "image": "imagesss/The-gate-2-01.jpg",
    "source": "image-local"
  },
  "@The Gate-x by Dev Aashish": {
    "profile8": [
      1.185,
      1.272,
      1.276,
      1.047,
      1.001,
      1.276,
      1.272,
      1.232
    ],
    "bands": [
      1,
      0.722,
      0.344
    ],
    "confidence": 1,
    "dominantColor": "#a59ca0",
    "image": "imagesss/The-gate-x-01.png",
    "source": "image-local"
  },
  "@The Gate-2 by Dev Aashish": {
    "profile8": [
      1.29,
      0.933,
      1.299,
      1.245,
      1.259,
      1.296,
      0.983,
      0.939
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#8ba0a8",
    "image": "imagesss/The-gate-2-01.jpg",
    "source": "image-local"
  },
  "@Amaryllis": {
    "profile8": [
      0.944,
      1.11,
      1.151,
      1.254,
      1.177,
      1.248,
      1.123,
      0.959
    ],
    "bands": [
      1,
      0.52,
      0.518
    ],
    "confidence": 1,
    "dominantColor": "#9aa4aa",
    "image": "imagesss/Amaryllis-01.jpg",
    "source": "image-local"
  },
  "@The Altitude": {
    "profile8": [
      0.903,
      0.94,
      1.272,
      1.089,
      1.258,
      1.199,
      1.088,
      0.91
    ],
    "bands": [
      1,
      0.52,
      0.516
    ],
    "confidence": 1,
    "dominantColor": "#b1a9af",
    "image": "imagesss/Altitude-02.jpg",
    "source": "image-local"
  },
  "@The August": {
    "profile8": [
      0.858,
      1.29,
      1.294,
      1.297,
      1.296,
      1.129,
      1.236,
      0.897
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#727b8e",
    "image": "imagesss/August-02.png",
    "source": "image-local"
  },
  "@Anamaya": {
    "profile8": [
      1.002,
      1.066,
      1.3,
      1.273,
      1.304,
      1.161,
      1.223,
      0.999
    ],
    "bands": [
      1,
      0.75,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#a49981",
    "image": "imagesss/Anammya-01.png",
    "source": "image-local"
  },
  "@Anantara Abode": {
    "profile8": [
      0.977,
      1.011,
      1.121,
      1.116,
      1.249,
      1.286,
      1.259,
      0.927
    ],
    "bands": [
      1,
      0.677,
      0.396
    ],
    "confidence": 1,
    "dominantColor": "#c3a689",
    "image": "imagesss/abode-01.jpg",
    "source": "image-local"
  },
  "@Anantara Imperial": {
    "profile8": [
      0.865,
      0.869,
      1.249,
      1.289,
      1.265,
      1.188,
      0.864,
      0.974
    ],
    "bands": [
      1,
      0.704,
      0.685
    ],
    "confidence": 1,
    "dominantColor": "#9ba0ab",
    "image": "imagesss/Imperial-01.jpg",
    "source": "image-local"
  },
  "@The Indus by Sheetal": {
    "profile8": [
      1.305,
      1.285,
      1.286,
      1.282,
      1.241,
      1.081,
      0.976,
      1.249
    ],
    "bands": [
      1,
      0.632,
      0.75
    ],
    "confidence": 1,
    "dominantColor": "#8d7e68",
    "image": "imagesss/indus-01.jpg",
    "source": "image-local"
  },
  "@Gharana by Sheetal": {
    "profile8": [
      1.039,
      1.299,
      1.215,
      1.112,
      1.162,
      1.249,
      1.305,
      1.039
    ],
    "bands": [
      1,
      0.95,
      0.815
    ],
    "confidence": 1,
    "dominantColor": "#52566d",
    "image": "imagesss/Gharana-03.png",
    "source": "image-local"
  },
  "@Centroid by Sanghvi Group": {
    "profile8": [
      0.93,
      0.929,
      1.261,
      1.265,
      1.168,
      1.047,
      0.965,
      0.935
    ],
    "bands": [
      1,
      0.52,
      0.404
    ],
    "confidence": 1,
    "dominantColor": "#5f799d",
    "image": "imagesss/centroid-01.jpg",
    "source": "image-local"
  },
  "@Manor Ananda": {
    "profile8": [
      0.957,
      0.968,
      1.268,
      1.286,
      1.296,
      1.301,
      1.299,
      1.08
    ],
    "bands": [
      1,
      0.52,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#a1a298",
    "image": "imagesss/manor-02.jpg",
    "source": "image-local"
  },
  "@Swati-Premier": {
    "profile8": [
      1.284,
      1.173,
      1.292,
      1.303,
      0.956,
      1.17,
      1.028,
      1.04
    ],
    "bands": [
      1,
      0.773,
      0.439
    ],
    "confidence": 1,
    "dominantColor": "#988b89",
    "image": "imagesss/swatiPremier-03.jpg",
    "source": "image-local"
  },
  "@Trident Experia": {
    "profile8": [
      1.103,
      1.294,
      1.283,
      1.285,
      1.264,
      1.235,
      1.212,
      1.071
    ],
    "bands": [
      1,
      0.802,
      0.51
    ],
    "confidence": 0.918,
    "dominantColor": "#605854",
    "image": "imagesss/tridentExperia-02.jpg",
    "source": "image-local"
  },
  "@Turquoise Rosedale": {
    "profile8": [
      0.96,
      1.215,
      1.295,
      1.22,
      1.211,
      0.888,
      0.9,
      0.903
    ],
    "bands": [
      1,
      0.566,
      0.518
    ],
    "confidence": 1,
    "dominantColor": "#5e7fbd",
    "image": "imagesss/Turquoise-Agasiya-01.jpg",
    "source": "image-local"
  },
  "@Turquoise Agasiya": {
    "profile8": [
      0.96,
      1.215,
      1.295,
      1.22,
      1.211,
      0.888,
      0.9,
      0.903
    ],
    "bands": [
      1,
      0.566,
      0.518
    ],
    "confidence": 1,
    "dominantColor": "#5e7fbd",
    "image": "imagesss/Turquoise-Agasiya-01.jpg",
    "source": "image-local"
  },
  "@Turquoise Glamouere": {
    "profile8": [
      1.121,
      1.227,
      1.24,
      1.172,
      1.137,
      1.08,
      0.893,
      0.902
    ],
    "bands": [
      1,
      0.766,
      0.511
    ],
    "confidence": 1,
    "dominantColor": "#438cbd",
    "image": "imagesss/Turquoise-Glamouere-02.jpg",
    "source": "image-local"
  },
  "@Suryam Arnath": {
    "profile8": [
      1.151,
      0.975,
      1.203,
      1.241,
      1.253,
      1.251,
      1.04,
      1.081
    ],
    "bands": [
      1,
      0.66,
      0.532
    ],
    "confidence": 0.882,
    "dominantColor": "#76726f",
    "image": "imagesss/suryam-03.jpg",
    "source": "image-local"
  },
  "@Radhe Govind Galaxy": {
    "profile8": [
      1.241,
      0.953,
      1.239,
      1.253,
      1.202,
      1.216,
      1.18,
      1.303
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#807f79",
    "image": "imagesss/web-fallback/radhe-govind-galaxy-web-1.png",
    "source": "image-web-fallback"
  },
  "@Swati 18": {
    "profile8": [
      0.98,
      0.951,
      0.961,
      1.132,
      1.223,
      1.257,
      1.11,
      0.986
    ],
    "bands": [
      1,
      0.52,
      0.45
    ],
    "confidence": 1,
    "dominantColor": "#a192aa",
    "image": "imagesss/swati18-01.jpg",
    "source": "image-local"
  },
  "@Swati Premier": {
    "profile8": [
      1.284,
      1.173,
      1.292,
      1.303,
      0.956,
      1.17,
      1.028,
      1.04
    ],
    "bands": [
      1,
      0.773,
      0.439
    ],
    "confidence": 1,
    "dominantColor": "#988b89",
    "image": "imagesss/swatiPremier-03.jpg",
    "source": "image-local"
  },
  "@Swati Signiya": {
    "profile8": [
      1.288,
      1.279,
      1.254,
      0.872,
      0.875,
      1.26,
      1.259,
      1.221
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9a9292",
    "image": "imagesss/swatiSigniya-01.jpg",
    "source": "image-local"
  },
  "@The Canvas by Kavisha": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Santorini Square": {
    "profile8": [
      1.001,
      1.276,
      1.267,
      1.199,
      1.199,
      1.124,
      1.012,
      0.984
    ],
    "bands": [
      1,
      0.52,
      0.376
    ],
    "confidence": 1,
    "dominantColor": "#968f91",
    "image": "imagesss/Shalin-square-3.jpeg",
    "source": "image-local"
  },
  "@Pearl Bungalow": {
    "profile8": [
      1.305,
      1.256,
      1.21,
      1.072,
      1.256,
      1.202,
      0.922,
      1.235
    ],
    "bands": [
      1,
      0.52,
      0.29
    ],
    "confidence": 1,
    "dominantColor": "#a8a39e",
    "image": "imagesss/web-fallback/pearl-bungalow-web-1.png",
    "source": "image-web-fallback"
  },
  "@Vaikunth By A.Shridhar": {
    "profile8": [
      1.15,
      1.043,
      1.082,
      1.146,
      1.165,
      1.249,
      1.291,
      1.301
    ],
    "bands": [
      1,
      0.864,
      0.318
    ],
    "confidence": 0.908,
    "dominantColor": "#7a8175",
    "image": "imagesss/Vaikunth-01.jpg",
    "source": "image-local"
  },
  "@Vivanta by A.Shridhar": {
    "profile8": [
      0.916,
      0.958,
      1.276,
      1.274,
      1.276,
      1.252,
      1.256,
      0.92
    ],
    "bands": [
      1,
      0.543,
      0.674
    ],
    "confidence": 1,
    "dominantColor": "#b59895",
    "image": "imagesss/Kaveri-03.jpeg",
    "source": "image-local"
  },
  "@Anantara Alora by A.Shridhar": {
    "profile8": [
      0.981,
      0.923,
      1.235,
      1.292,
      1.304,
      1.297,
      1.302,
      1.299
    ],
    "bands": [
      1,
      0.52,
      0.372
    ],
    "confidence": 1,
    "dominantColor": "#8b9497",
    "image": "imagesss/Alora-01.jpg",
    "source": "image-local"
  },
  "@Wynn by A.Shridhar": {
    "profile8": [
      0.91,
      0.973,
      1.026,
      1.278,
      1.281,
      1.257,
      0.975,
      0.959
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#9d9ca3",
    "image": "imagesss/Wynn-02.jpg",
    "source": "image-local"
  },
  "@Athens by A.Shridhar": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Absolute by A.Shridhar": {
    "profile8": [
      1.297,
      1.253,
      1.217,
      1.143,
      1.146,
      1.133,
      1.278,
      1.301
    ],
    "bands": [
      1,
      0.95,
      0.662
    ],
    "confidence": 0.717,
    "dominantColor": "#857950",
    "image": "imagesss/Absolute-02.jpg",
    "source": "image-local"
  },
  "@Kalrav Nest by A.Shridhar": {
    "profile8": [
      1.297,
      1.301,
      1.298,
      1.263,
      1.298,
      1.263,
      1.269,
      1.264
    ],
    "bands": [
      1,
      0.782,
      0.82
    ],
    "confidence": 0.426,
    "dominantColor": "#627972",
    "image": "imagesss/The-Nest-03.jpg",
    "source": "image-local"
  },
  "@Silver Harmony-2": {
    "profile8": [
      1.09,
      1.125,
      1.149,
      1.22,
      1.274,
      1.268,
      1.269,
      1.302
    ],
    "bands": [
      1,
      0.859,
      0.772
    ],
    "confidence": 0.905,
    "dominantColor": "#867741",
    "image": "imagesss/silver-spring-01.jpg",
    "source": "image-local"
  },
  "@Centre Court by Trogon": {
    "profile8": [
      1.02,
      1.009,
      1.298,
      1.281,
      1.302,
      1.221,
      1.275,
      1.246
    ],
    "bands": [
      1,
      0.895,
      0.724
    ],
    "confidence": 1,
    "dominantColor": "#5f5d3b",
    "image": "imagesss/Centre-Court-02.jpeg",
    "source": "image-local"
  },
  "@Trogon Twin Towers": {
    "profile8": [
      1.288,
      0.961,
      1.257,
      1.218,
      1.1,
      1.266,
      0.903,
      1.2
    ],
    "bands": [
      1,
      0.681,
      0.597
    ],
    "confidence": 1,
    "dominantColor": "#6c839d",
    "image": "imagesss/Trogon-Twin-01.jpg",
    "source": "image-local"
  },
  "@Swarnim Sun": {
    "profile8": [
      0.906,
      1.186,
      1.223,
      1.218,
      1.223,
      1.223,
      1.093,
      0.926
    ],
    "bands": [
      1,
      0.685,
      0.63
    ],
    "confidence": 1,
    "dominantColor": "#98a2b8",
    "image": "imagesss/Swarnim-sun-01.jpeg",
    "source": "image-local"
  },
  "@Swarnim Sentosaa": {
    "profile8": [
      0.913,
      1.087,
      1.115,
      1.152,
      1.185,
      1.227,
      1.285,
      1.242
    ],
    "bands": [
      1,
      0.824,
      0.559
    ],
    "confidence": 1,
    "dominantColor": "#5d75af",
    "image": "imagesss/Swarnim-18-01.jpg",
    "source": "image-local"
  },
  "@Swarnim 18": {
    "profile8": [
      0.913,
      1.087,
      1.115,
      1.152,
      1.185,
      1.227,
      1.285,
      1.242
    ],
    "bands": [
      1,
      0.824,
      0.559
    ],
    "confidence": 1,
    "dominantColor": "#5d75af",
    "image": "imagesss/Swarnim-18-01.jpg",
    "source": "image-local"
  },
  "@Swarnim Business Center": {
    "profile8": [
      0.961,
      0.961,
      1.112,
      1.261,
      1.295,
      1.213,
      0.98,
      0.961
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#7aacd7",
    "image": "imagesss/Swarnim-Buis-02.png",
    "source": "image-local"
  },
  "@Siban 65": {
    "profile8": [
      0.914,
      1.211,
      1.185,
      1.246,
      1.226,
      1.233,
      1.299,
      1.106
    ],
    "bands": [
      1,
      0.612,
      0.662
    ],
    "confidence": 1,
    "dominantColor": "#869caf",
    "image": "imagesss/Siban-03.jpg",
    "source": "image-local"
  },
  "@Siban": {
    "profile8": [
      0.914,
      1.211,
      1.185,
      1.246,
      1.226,
      1.233,
      1.299,
      1.106
    ],
    "bands": [
      1,
      0.612,
      0.662
    ],
    "confidence": 1,
    "dominantColor": "#869caf",
    "image": "imagesss/Siban-03.jpg",
    "source": "image-local"
  },
  "@Turquoise Grandeure": {
    "profile8": [
      0.96,
      1.215,
      1.295,
      1.22,
      1.211,
      0.888,
      0.9,
      0.903
    ],
    "bands": [
      1,
      0.566,
      0.518
    ],
    "confidence": 1,
    "dominantColor": "#5e7fbd",
    "image": "imagesss/Turquoise-Agasiya-01.jpg",
    "source": "image-local"
  },
  "@Citadel": {
    "profile8": [
      0.961,
      0.959,
      1.106,
      1.304,
      1.3,
      1.12,
      0.971,
      0.955
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#9b9287",
    "image": "imagesss/Citadel-01.jpg",
    "source": "image-local"
  },
  "@Rewa": {
    "profile8": [
      0.972,
      1.125,
      1.134,
      1.207,
      1.242,
      1.291,
      1.205,
      1.009
    ],
    "bands": [
      1,
      0.804,
      0.63
    ],
    "confidence": 1,
    "dominantColor": "#8c8c78",
    "image": "imagesss/Rewa-01.jpg",
    "source": "image-local"
  },
  "@Celestial Garden Living": {
    "profile8": [
      1.058,
      1.162,
      1.187,
      1.249,
      1.239,
      1.2,
      1.169,
      0.973
    ],
    "bands": [
      1,
      0.617,
      0.649
    ],
    "confidence": 0.923,
    "dominantColor": "#b19178",
    "image": "imagesss/Siddharth-Gardenia-3.jpeg",
    "source": "image-local"
  },
  "@Ananta Elite": {
    "profile8": [
      1.129,
      1.193,
      1.241,
      1.254,
      1.278,
      0.911,
      0.948,
      1.007
    ],
    "bands": [
      1,
      0.843,
      0.729
    ],
    "confidence": 1,
    "dominantColor": "#a0a6a1",
    "image": "imagesss/ananta-01.jpg",
    "source": "image-local"
  },
  "@Rajul Greens": {
    "profile8": [
      0.932,
      0.912,
      1.242,
      1.266,
      1.102,
      1.107,
      1.28,
      1.282
    ],
    "bands": [
      1,
      0.52,
      0.298
    ],
    "confidence": 1,
    "dominantColor": "#a19ead",
    "image": "imagesss/Olive-Greens-02.jpeg",
    "source": "image-local"
  },
  "@The First": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Zade Luxuria": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "@Vinayak Elysium": {
    "profile8": [
      0.978,
      1.151,
      1.194,
      1.232,
      1.286,
      1.225,
      0.871,
      0.862
    ],
    "bands": [
      1,
      0.833,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#94a2b4",
    "image": "imagesss/vinayak-elysium-01.jpg",
    "source": "image-local"
  },
  "@Anand Avyam": {
    "profile8": [
      1.238,
      1.272,
      1.242,
      1.207,
      0.964,
      1.056,
      1.098,
      1.085
    ],
    "bands": [
      1,
      0.95,
      0.797
    ],
    "confidence": 0.935,
    "dominantColor": "#9280a7",
    "image": "imagesss/anand-avyam-02.jpeg",
    "source": "image-local"
  },
  "@Avant": {
    "profile8": [
      1.256,
      1.099,
      1.037,
      1.199,
      1.288,
      1.3,
      1.295,
      1.302
    ],
    "bands": [
      1,
      0.756,
      0.698
    ],
    "confidence": 0.955,
    "dominantColor": "#7d7748",
    "image": "imagesss/avant-02.jpg",
    "source": "image-local"
  },
  "@Eternity by Ratnaakar": {
    "profile8": [
      0.877,
      1.062,
      1.14,
      1.243,
      1.274,
      1.194,
      1.121,
      0.866
    ],
    "bands": [
      1,
      0.95,
      0.603
    ],
    "confidence": 1,
    "dominantColor": "#8797c6",
    "image": "imagesss/Eternity-03.jpeg",
    "source": "image-local"
  },
  "@Artesia by Ratnaakar": {
    "profile8": [
      0.959,
      1.302,
      1.278,
      1.254,
      1.233,
      1.197,
      1.179,
      1.158
    ],
    "bands": [
      1,
      0.892,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#ab9ca0",
    "image": "imagesss/Artesia-01.png",
    "source": "image-local"
  },
  "@The Whitecraft": {
    "profile8": [
      0.934,
      0.959,
      1.217,
      1.27,
      1.273,
      0.984,
      0.865,
      0.868
    ],
    "bands": [
      1,
      0.703,
      0.672
    ],
    "confidence": 1,
    "dominantColor": "#81b5ea",
    "image": "imagesss/TheWhitecraft-01.jpg",
    "source": "image-local"
  },
  "@Belmont by Binori": {
    "profile8": [
      0.945,
      0.945,
      1.06,
      1.193,
      1.28,
      1.09,
      1.298,
      1.176
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#8fb4bd",
    "image": "imagesss/Binori-belmont-01.jpeg",
    "source": "image-local"
  },
  "@Triveni 84": {
    "profile8": [
      0.943,
      0.898,
      0.973,
      1.261,
      1.247,
      1.174,
      0.892,
      1.251
    ],
    "bands": [
      1,
      0.52,
      0.466
    ],
    "confidence": 1,
    "dominantColor": "#b1a8a3",
    "image": "imagesss/Triveni84-02.png",
    "source": "image-local"
  },
  "@Anamika High Point": {
    "profile8": [
      1.007,
      1.19,
      1.268,
      1.305,
      1.304,
      1.232,
      1.191,
      0.969
    ],
    "bands": [
      1,
      0.814,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#7283a4",
    "image": "imagesss/anamika-01.jpg",
    "source": "image-local"
  },
  "@The Double 3": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "@Sky Park": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "@The Park": {
    "profile8": [
      1.114,
      0.99,
      1.14,
      1.139,
      1.181,
      1.221,
      1.239,
      1.054
    ],
    "bands": [
      1,
      0.933,
      0.522
    ],
    "confidence": 0.774,
    "dominantColor": "#526e72",
    "image": "imagesss/The-North-Park-02.jpg",
    "source": "image-local"
  },
  "@Turquoise Greenz by Ratna": {
    "profile8": [
      0.96,
      1.215,
      1.295,
      1.22,
      1.211,
      0.888,
      0.9,
      0.903
    ],
    "bands": [
      1,
      0.566,
      0.518
    ],
    "confidence": 1,
    "dominantColor": "#5e7fbd",
    "image": "imagesss/Turquoise-Agasiya-01.jpg",
    "source": "image-local"
  },
  "@The Residency": {
    "profile8": [
      0.875,
      1.178,
      1.243,
      1.268,
      1.251,
      1.234,
      1.213,
      1.211
    ],
    "bands": [
      1,
      0.829,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#846f74",
    "image": "imagesss/The-Residency-01.jpg",
    "source": "image-local"
  },
  "@The Bellagio": {
    "profile8": [
      1.302,
      1.185,
      1.304,
      1.276,
      1.219,
      1.166,
      0.929,
      0.859
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#99948b",
    "image": "imagesss/The-Bellagio-01.png",
    "source": "image-local"
  },
  "@Eternity by Sankalp": {
    "profile8": [
      1.255,
      1.301,
      1.172,
      1.137,
      1.158,
      1.217,
      1.216,
      1.178
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.724,
    "dominantColor": "#ac8d77",
    "image": "imagesss/Sankalp-Eternity-03.png",
    "source": "image-local"
  },
  "@Sankalp 59": {
    "profile8": [
      0.867,
      0.871,
      1.204,
      1.261,
      1.303,
      1.104,
      0.899,
      1.189
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#7d9eb0",
    "image": "imagesss/sankalp-480-01.jpg",
    "source": "image-local"
  },
  "@Sankalp 480": {
    "profile8": [
      0.867,
      0.871,
      1.204,
      1.261,
      1.303,
      1.104,
      0.899,
      1.189
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#7d9eb0",
    "image": "imagesss/sankalp-480-01.jpg",
    "source": "image-local"
  },
  "@Olive XIV": {
    "profile8": [
      0.957,
      0.953,
      1.227,
      1.212,
      1.303,
      0.956,
      0.952,
      0.993
    ],
    "bands": [
      1,
      0.52,
      0.4
    ],
    "confidence": 1,
    "dominantColor": "#838f83",
    "image": "imagesss/Olive-XIV-01.jpg",
    "source": "image-local"
  },
  "@Apricus 2 by Saiyamm": {
    "profile8": [
      1.092,
      1.2,
      1.291,
      1.276,
      1.078,
      1.23,
      1.279,
      1.069
    ],
    "bands": [
      1,
      0.865,
      0.563
    ],
    "confidence": 1,
    "dominantColor": "#686760",
    "image": "imagesss/apricus-02.jpg",
    "source": "image-local"
  },
  "@Times Marvel": {
    "profile8": [
      1.304,
      1.291,
      0.878,
      0.998,
      1.274,
      0.917,
      0.932,
      0.86
    ],
    "bands": [
      1,
      0.911,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9fc5d8",
    "image": "imagesss/Marvel-02.jpg",
    "source": "image-local"
  },
  "@Times Trinity": {
    "profile8": [
      0.899,
      0.919,
      0.957,
      1.214,
      1.256,
      1.183,
      0.916,
      0.906
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#a4b6c2",
    "image": "imagesss/times-104-02.jpg",
    "source": "image-local"
  },
  "@Times 104": {
    "profile8": [
      0.899,
      0.919,
      0.957,
      1.214,
      1.256,
      1.183,
      0.916,
      0.906
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#a4b6c2",
    "image": "imagesss/times-104-02.jpg",
    "source": "image-local"
  },
  "@Times 40": {
    "profile8": [
      1.268,
      1.06,
      1.057,
      1.218,
      1.267,
      1.282,
      1.283,
      1.283
    ],
    "bands": [
      1,
      0.792,
      0.542
    ],
    "confidence": 1,
    "dominantColor": "#7a5a3d",
    "image": "imagesss/times-40-01.jpg",
    "source": "image-local"
  },
  "@Tree Top by Sheladia": {
    "profile8": [
      1.151,
      1.053,
      1.07,
      1.209,
      1.086,
      1.3,
      1.291,
      1.239
    ],
    "bands": [
      1,
      0.95,
      0.7
    ],
    "confidence": 0.92,
    "dominantColor": "#7a7941",
    "image": "imagesss/tree-top-03.jpeg",
    "source": "image-local"
  },
  "@Swan Lake": {
    "profile8": [
      1.254,
      0.915,
      0.897,
      1.288,
      1.288,
      0.995,
      1.302,
      1.29
    ],
    "bands": [
      1,
      0.52,
      0.357
    ],
    "confidence": 1,
    "dominantColor": "#c0b9ae",
    "image": "imagesss/solo-lake-view-01.jpg",
    "source": "image-local"
  },
  "@The Sovereign": {
    "profile8": [
      0.879,
      0.859,
      1.226,
      1.294,
      1.25,
      1.281,
      0.884,
      0.858
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#7791c0",
    "image": "imagesss/sovereign-01.jpg",
    "source": "image-local"
  },
  "@Sharanya Kadamb": {
    "profile8": [
      1.297,
      1.302,
      1.121,
      1.246,
      1.216,
      1.296,
      1.278,
      1.017
    ],
    "bands": [
      1,
      0.69,
      0.704
    ],
    "confidence": 0.866,
    "dominantColor": "#977453",
    "image": "imagesss/Kadamb-02.png",
    "source": "image-local"
  },
  "@Sakar One": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "The Quad": {
    "profile8": [
      0.861,
      0.861,
      1,
      1.225,
      1.171,
      1.094,
      0.859,
      0.862
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#6585a8",
    "image": "imagesss/quad-10.jpeg",
    "source": "image-local"
  },
  "The Sky View": {
    "profile8": [
      1.218,
      1.171,
      1.199,
      1.119,
      1.28,
      1.302,
      1.071,
      0.859
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#677592",
    "image": "imagesss/sky-view-02.jpg",
    "source": "image-local"
  },
  "Sun Urban Park": {
    "profile8": [
      0.993,
      1.044,
      0.997,
      1.214,
      1.225,
      1.185,
      1.104,
      1.102
    ],
    "bands": [
      1,
      0.95,
      0.529
    ],
    "confidence": 0.899,
    "dominantColor": "#99a8b0",
    "image": "imagesss/urban-park-01.jpg",
    "source": "image-local"
  },
  "Sun Mayfair": {
    "profile8": [
      0.861,
      1.201,
      1.247,
      1.284,
      1.224,
      1.215,
      1.132,
      0.948
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#9c8377",
    "image": "imagesss/Sunflower-01.png",
    "source": "image-local"
  },
  "Sun Park West": {
    "profile8": [
      1.113,
      1.201,
      1.188,
      1.219,
      1.288,
      1.304,
      1.28,
      1.178
    ],
    "bands": [
      1,
      0.948,
      0.792
    ],
    "confidence": 0.844,
    "dominantColor": "#758446",
    "image": "imagesss/The-Westpark-01.jpeg",
    "source": "image-local"
  },
  "Sun City Park": {
    "profile8": [
      1.205,
      1.294,
      1.209,
      1.276,
      0.978,
      1.207,
      1.218,
      1.223
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.822,
    "dominantColor": "#575372",
    "image": "imagesss/city-park-01.jpg",
    "source": "image-local"
  },
  "Sun Footprint": {
    "profile8": [
      0.994,
      1.199,
      1.208,
      1.263,
      1.272,
      1.266,
      1.27,
      1.265
    ],
    "bands": [
      1,
      0.876,
      0.82
    ],
    "confidence": 0.928,
    "dominantColor": "#af9869",
    "image": "imagesss/Sun-orbit-1.jpg",
    "source": "image-local"
  },
  "Sun Solace": {
    "profile8": [
      0.994,
      1.199,
      1.208,
      1.263,
      1.272,
      1.266,
      1.27,
      1.265
    ],
    "bands": [
      1,
      0.876,
      0.82
    ],
    "confidence": 0.928,
    "dominantColor": "#af9869",
    "image": "imagesss/Sun-orbit-1.jpg",
    "source": "image-local"
  },
  "Sun Silver Springs": {
    "profile8": [
      1.09,
      1.125,
      1.149,
      1.22,
      1.274,
      1.268,
      1.269,
      1.302
    ],
    "bands": [
      1,
      0.859,
      0.772
    ],
    "confidence": 0.905,
    "dominantColor": "#867741",
    "image": "imagesss/silver-spring-01.jpg",
    "source": "image-local"
  },
  "Armonia Sky": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "Vishakha Seleqt": {
    "profile8": [
      1.212,
      1.212,
      1.212,
      0.997,
      0.987,
      1.18,
      1.215,
      1.154
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 0.911,
    "dominantColor": "#bcafa7",
    "image": "imagesss/Seleqt-01.jpg",
    "source": "image-local"
  },
  "Arise One": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "Pre Launch By Sun Builders": {
    "profile8": [
      1.298,
      1.302,
      1.228,
      1.007,
      1.02,
      0.918,
      0.957,
      0.9
    ],
    "bands": [
      1,
      0.52,
      0.7
    ],
    "confidence": 1,
    "dominantColor": "#ccb9a9",
    "image": "imagesss/premier-01.png",
    "source": "image-local"
  },
  "Essence 171": {
    "profile8": [
      1.013,
      1.242,
      1.29,
      1.214,
      1.134,
      1.061,
      1.045,
      0.89
    ],
    "bands": [
      1,
      0.95,
      0.573
    ],
    "confidence": 1,
    "dominantColor": "#8499b7",
    "image": "imagesss/Vivaan-Essence-01.jpeg",
    "source": "image-local"
  },
  "The One": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "Dev Aurram Minato": {
    "profile8": [
      0.94,
      1.171,
      1.24,
      1.289,
      1.254,
      1.15,
      1.012,
      0.923
    ],
    "bands": [
      1,
      0.703,
      0.637
    ],
    "confidence": 1,
    "dominantColor": "#83979e",
    "image": "imagesss/dev-aurram-01.jpg",
    "source": "image-local"
  },
  "Aanira One": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "Diwali Skyz": {
    "profile8": [
      0.951,
      1.138,
      1.095,
      1.225,
      1.268,
      1.172,
      0.966,
      0.937
    ],
    "bands": [
      1,
      0.52,
      0.37
    ],
    "confidence": 1,
    "dominantColor": "#937f7c",
    "image": "imagesss/diwali-sky-01.jpeg",
    "source": "image-local"
  },
  "Panache": {
    "profile8": [
      1.123,
      1.268,
      1.194,
      1.235,
      1.201,
      1.161,
      1.067,
      0.924
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#867574",
    "image": "imagesss/panache-02.jpg",
    "source": "image-local"
  },
  "Sarang Lake View": {
    "profile8": [
      1.254,
      0.915,
      0.897,
      1.288,
      1.288,
      0.995,
      1.302,
      1.29
    ],
    "bands": [
      1,
      0.52,
      0.357
    ],
    "confidence": 1,
    "dominantColor": "#c0b9ae",
    "image": "imagesss/solo-lake-view-01.jpg",
    "source": "image-local"
  },
  "Ganesh Vivanta": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "Indraprasth Marigold": {
    "profile8": [
      1.262,
      1.154,
      1.116,
      1.099,
      1.108,
      1.136,
      1.044,
      1.304
    ],
    "bands": [
      1,
      0.95,
      0.438
    ],
    "confidence": 0.978,
    "dominantColor": "#686146",
    "image": "imagesss/marigold-02.jpg",
    "source": "image-local"
  },
  "Indraprasth Ixora": {
    "profile8": [
      1.285,
      1.281,
      1.259,
      1.136,
      1.115,
      1.24,
      1.271,
      1.251
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.672,
    "dominantColor": "#746b64",
    "image": "imagesss/ixora-02.jpg",
    "source": "image-local"
  },
  "Indraprasth Abode": {
    "profile8": [
      0.977,
      1.011,
      1.121,
      1.116,
      1.249,
      1.286,
      1.259,
      0.927
    ],
    "bands": [
      1,
      0.677,
      0.396
    ],
    "confidence": 1,
    "dominantColor": "#c3a689",
    "image": "imagesss/abode-01.jpg",
    "source": "image-local"
  },
  "Swarnim Heights": {
    "profile8": [
      1.204,
      0.862,
      1.275,
      1.151,
      1.016,
      1.083,
      0.859,
      0.869
    ],
    "bands": [
      1,
      0.786,
      0.571
    ],
    "confidence": 1,
    "dominantColor": "#79a1c5",
    "image": "imagesss/swarnim-heights-01.jpg",
    "source": "image-local"
  },
  "Indraprasth Saptak": {
    "profile8": [
      1.088,
      1.132,
      1.129,
      1.127,
      1.177,
      1.138,
      1.112,
      1.087
    ],
    "bands": [
      1,
      0.75,
      0.49
    ],
    "confidence": 0.57,
    "dominantColor": "#8f9188",
    "image": "imagesss/indraprasth-abode.jpg",
    "source": "image-local"
  },
  "Ananta": {
    "profile8": [
      1.129,
      1.193,
      1.241,
      1.254,
      1.278,
      0.911,
      0.948,
      1.007
    ],
    "bands": [
      1,
      0.843,
      0.729
    ],
    "confidence": 1,
    "dominantColor": "#a0a6a1",
    "image": "imagesss/ananta-01.jpg",
    "source": "image-local"
  },
  "The Q By Satya": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "Anuvrat By Shivanka": {
    "profile8": [
      0.875,
      1.226,
      1.279,
      1.252,
      1.225,
      1.09,
      1.139,
      0.901
    ],
    "bands": [
      1,
      0.689,
      0.721
    ],
    "confidence": 1,
    "dominantColor": "#6d6671",
    "image": "imagesss/Anuvrat-02.jpg",
    "source": "image-local"
  },
  "Anuvrat": {
    "profile8": [
      0.875,
      1.226,
      1.279,
      1.252,
      1.225,
      1.09,
      1.139,
      0.901
    ],
    "bands": [
      1,
      0.689,
      0.721
    ],
    "confidence": 1,
    "dominantColor": "#6d6671",
    "image": "imagesss/Anuvrat-02.jpg",
    "source": "image-local"
  },
  "Scarlet Springs": {
    "profile8": [
      1.258,
      1.248,
      1.109,
      1.125,
      1.258,
      1.261,
      1.246,
      1.246
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.868,
    "dominantColor": "#67758b",
    "image": "imagesss/Scarlet-Springs-02.jpg",
    "source": "image-local"
  },
  "Signet": {
    "profile8": [
      1.009,
      1.302,
      1.156,
      1.157,
      1.177,
      1.251,
      1.284,
      1.165
    ],
    "bands": [
      1,
      0.95,
      0.733
    ],
    "confidence": 0.847,
    "dominantColor": "#849395",
    "image": "imagesss/Signet-01.jpg",
    "source": "image-local"
  },
  "The Crest": {
    "profile8": [
      0.875,
      0.928,
      1.187,
      1.252,
      1.3,
      1.303,
      0.939,
      0.871
    ],
    "bands": [
      1,
      0.806,
      0.806
    ],
    "confidence": 1,
    "dominantColor": "#a5a9ce",
    "image": "imagesss/The-Crest-02.jpg",
    "source": "image-local"
  },
  "Solo Lake View": {
    "profile8": [
      1.254,
      0.915,
      0.897,
      1.288,
      1.288,
      0.995,
      1.302,
      1.29
    ],
    "bands": [
      1,
      0.52,
      0.357
    ],
    "confidence": 1,
    "dominantColor": "#c0b9ae",
    "image": "imagesss/solo-lake-view-01.jpg",
    "source": "image-local"
  },
  "Ideal Ixora": {
    "profile8": [
      1.285,
      1.281,
      1.259,
      1.136,
      1.115,
      1.24,
      1.271,
      1.251
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.672,
    "dominantColor": "#746b64",
    "image": "imagesss/ixora-02.jpg",
    "source": "image-local"
  },
  "The Green Parmeshwar": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "Shaligram Luxuria": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "Dharti Sky Line": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "Nityam Harmony": {
    "profile8": [
      1.212,
      1.214,
      1.212,
      1.079,
      1.148,
      1.212,
      1.212,
      1.142
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.805,
    "dominantColor": "#8e7c71",
    "image": "imagesss/Silver-Harmony-02.png",
    "source": "image-local"
  },
  "The Sparkle": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "Shaligram Sky": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "Status Sky": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "Harmony Harikesh": {
    "profile8": [
      1.212,
      1.214,
      1.212,
      1.079,
      1.148,
      1.212,
      1.212,
      1.142
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.805,
    "dominantColor": "#8e7c71",
    "image": "imagesss/Silver-Harmony-02.png",
    "source": "image-local"
  },
  "Vivekanand Arise": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "Yash Imperia": {
    "profile8": [
      0.865,
      0.869,
      1.249,
      1.289,
      1.265,
      1.188,
      0.864,
      0.974
    ],
    "bands": [
      1,
      0.704,
      0.685
    ],
    "confidence": 1,
    "dominantColor": "#9ba0ab",
    "image": "imagesss/Imperial-01.jpg",
    "source": "image-local"
  },
  "Addor Arise": {
    "profile8": [
      0.977,
      1.087,
      1.187,
      1.297,
      1.253,
      1.271,
      1.015,
      0.959
    ],
    "bands": [
      1,
      0.787,
      0.617
    ],
    "confidence": 1,
    "dominantColor": "#8f8495",
    "image": "imagesss/arise-one-01.jpg",
    "source": "image-local"
  },
  "Prism": {
    "profile8": [
      0.951,
      1.156,
      1.187,
      1.188,
      1.186,
      1.181,
      1.15,
      0.915
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 0.951,
    "dominantColor": "#b5aca5",
    "image": "imagesss/atham-prism-02.jpg",
    "source": "image-local"
  },
  "Terrace Skyline": {
    "profile8": [
      0.966,
      0.961,
      1.214,
      1.303,
      1.169,
      1.066,
      1.11,
      1.121
    ],
    "bands": [
      1,
      0.52,
      0.424
    ],
    "confidence": 1,
    "dominantColor": "#96948f",
    "image": "imagesss/Skyline-01.jpeg",
    "source": "image-local"
  },
  "Skyrise": {
    "profile8": [
      0.891,
      0.969,
      1.264,
      1.264,
      1.264,
      1.264,
      0.928,
      0.903
    ],
    "bands": [
      1,
      0.722,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#cbb9ad",
    "image": "imagesss/skyrise-01.jpg",
    "source": "image-local"
  },
  "Swastik Square": {
    "profile8": [
      1.001,
      1.276,
      1.267,
      1.199,
      1.199,
      1.124,
      1.012,
      0.984
    ],
    "bands": [
      1,
      0.52,
      0.376
    ],
    "confidence": 1,
    "dominantColor": "#968f91",
    "image": "imagesss/Shalin-square-3.jpeg",
    "source": "image-local"
  },
  "Nirman Sahvas": {
    "profile8": [
      1.047,
      1.152,
      1.188,
      1.198,
      1.237,
      0.944,
      1.297,
      1.052
    ],
    "bands": [
      1,
      0.602,
      0.581
    ],
    "confidence": 1,
    "dominantColor": "#93928d",
    "image": "imagesss/nirman-sahvas-02.jpg",
    "source": "image-local"
  },
  "The Aayansh": {
    "profile8": [
      0.941,
      1.17,
      1.258,
      1.133,
      1.086,
      1.258,
      1.217,
      0.948
    ],
    "bands": [
      1,
      0.698,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#aaa4a0",
    "image": "imagesss/the-aayansh-01.jpg",
    "source": "image-local"
  },
  "Sharnam Aayan": {
    "profile8": [
      0.947,
      1.297,
      1.293,
      1.031,
      1.042,
      1.292,
      1.298,
      0.902
    ],
    "bands": [
      1,
      0.52,
      0.423
    ],
    "confidence": 1,
    "dominantColor": "#a88c79",
    "image": "imagesss/sharnam-aayan-01.jpg",
    "source": "image-local"
  },
  "The Verity": {
    "profile8": [
      1.018,
      1.292,
      1.175,
      1.268,
      1.283,
      1.292,
      1.254,
      0.938
    ],
    "bands": [
      1,
      0.857,
      0.82
    ],
    "confidence": 1,
    "dominantColor": "#78778a",
    "image": "imagesss/Athens-01.jpg",
    "source": "image-local"
  },
  "Aaloka": {
    "profile8": [
      1.228,
      0.906,
      1.174,
      1.207,
      1.204,
      1.212,
      1.22,
      1.304
    ],
    "bands": [
      1,
      0.603,
      0.726
    ],
    "confidence": 1,
    "dominantColor": "#8b9ed0",
    "image": "imagesss/aaloka-02.jpg",
    "source": "image-local"
  },
  "Signor Heritage": {
    "profile8": [
      1.284,
      0.979,
      1.281,
      1.224,
      1.237,
      1.282,
      0.897,
      1.198
    ],
    "bands": [
      1,
      0.52,
      0.28
    ],
    "confidence": 1,
    "dominantColor": "#a8bbcb",
    "image": "imagesss/signor-heritage-01.jpg",
    "source": "image-local"
  },
  "Shivam Sky": {
    "profile8": [
      0.913,
      1.258,
      1.228,
      1.282,
      1.234,
      1.2,
      1.22,
      1.011
    ],
    "bands": [
      1,
      0.901,
      0.479
    ],
    "confidence": 1,
    "dominantColor": "#8792a0",
    "image": "imagesss/dharti-sky-line-02.jpg",
    "source": "image-local"
  },
  "Onyx Luxuria": {
    "profile8": [
      0.967,
      0.953,
      1.089,
      1.252,
      1.252,
      1.212,
      0.936,
      1.034
    ],
    "bands": [
      1,
      0.52,
      0.406
    ],
    "confidence": 1,
    "dominantColor": "#9d9c9f",
    "image": "imagesss/Ganesh-Luxuria-01.jpeg",
    "source": "image-local"
  },
  "Anant Parmeshwar": {
    "profile8": [
      1.129,
      1.193,
      1.241,
      1.254,
      1.278,
      0.911,
      0.948,
      1.007
    ],
    "bands": [
      1,
      0.843,
      0.729
    ],
    "confidence": 1,
    "dominantColor": "#a0a6a1",
    "image": "imagesss/ananta-01.jpg",
    "source": "image-local"
  },
  "Swarnim Skyline": {
    "profile8": [
      1.202,
      1.129,
      1.137,
      1.279,
      1.303,
      1.249,
      1.035,
      1.011
    ],
    "bands": [
      1,
      0.675,
      0.584
    ],
    "confidence": 1,
    "dominantColor": "#9b9fa4",
    "image": "imagesss/swarnim-skyline-01.jpg",
    "source": "image-local"
  },
  "Shaligram Pride": {
    "profile8": [
      1.253,
      1.292,
      1.248,
      1.198,
      1.244,
      1.253,
      1.188,
      1.202
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.705,
    "dominantColor": "#72696d",
    "image": "imagesss/Super-Shaligram-01.jpg",
    "source": "image-local"
  },
  "Shaligram Prestige": {
    "profile8": [
      1.253,
      1.292,
      1.248,
      1.198,
      1.244,
      1.253,
      1.188,
      1.202
    ],
    "bands": [
      1,
      0.95,
      0.82
    ],
    "confidence": 0.705,
    "dominantColor": "#72696d",
    "image": "imagesss/Super-Shaligram-01.jpg",
    "source": "image-local"
  },
  "ManekBaug Society": {
    "profile8": [
      1.069,
      0.932,
      0.934,
      0.896,
      1.078,
      0.94,
      0.963,
      0.905
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kalrav Treasure by A.Shridhar": {
    "profile8": [
      0.983,
      0.905,
      0.987,
      0.909,
      0.974,
      0.976,
      0.978,
      0.901
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Reva": {
    "profile8": [
      0.961,
      0.919,
      0.965,
      0.923,
      1.032,
      0.91,
      0.956,
      0.914
    ],
    "bands": [
      1,
      0.66,
      0.35
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Narmada": {
    "profile8": [
      1.013,
      0.911,
      0.957,
      0.955,
      1.004,
      0.902,
      0.969,
      0.946
    ],
    "bands": [
      1,
      0.66,
      0.35
    ],
    "confidence": 0.22,
    "dominantColor": "#6ec8ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Ganga": {
    "profile8": [
      1.046,
      0.944,
      0.902,
      0.899,
      1.055,
      0.953,
      0.93,
      0.908
    ],
    "bands": [
      1,
      0.66,
      0.35
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Keshwam Skyview": {
    "profile8": [
      0.977,
      0.774,
      0.992,
      0.79,
      0.968,
      0.786,
      1.023,
      0.841
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Satyamev Luxor": {
    "profile8": [
      0.969,
      0.767,
      0.985,
      0.782,
      0.96,
      0.778,
      1.016,
      0.834
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kautilya TWO20": {
    "profile8": [
      1.012,
      0.889,
      1.027,
      0.825,
      1,
      0.918,
      0.996,
      0.894
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Sakar Two": {
    "profile8": [
      1.076,
      0.894,
      0.941,
      0.938,
      1.005,
      0.903,
      0.969,
      0.947
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#b58cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Sakar Three": {
    "profile8": [
      1.049,
      0.946,
      0.904,
      0.902,
      1.057,
      0.955,
      0.933,
      0.911
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Skyview 126": {
    "profile8": [
      1.003,
      0.765,
      0.947,
      0.79,
      0.994,
      0.776,
      1.059,
      0.841
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Akshar Evoq": {
    "profile8": [
      1.013,
      0.955,
      0.957,
      0.919,
      1.004,
      0.946,
      0.968,
      0.91
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Stateland": {
    "profile8": [
      1.028,
      0.746,
      0.973,
      0.77,
      1.037,
      0.775,
      1.021,
      0.839
    ],
    "bands": [
      1,
      0.66,
      0.35
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Vishakha Empyrean": {
    "profile8": [
      0.981,
      0.779,
      1.005,
      0.723,
      0.972,
      0.79,
      1.036,
      0.854
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Veridian": {
    "profile8": [
      0.993,
      0.791,
      1.018,
      0.736,
      0.984,
      0.802,
      1.049,
      0.787
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Addor Aspire 2": {
    "profile8": [
      1.074,
      0.892,
      0.929,
      0.927,
      1.065,
      0.883,
      0.941,
      0.918
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#b58cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aristo Avira": {
    "profile8": [
      1.028,
      0.951,
      0.944,
      0.866,
      1.02,
      0.942,
      0.935,
      0.937
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aristo Anantam": {
    "profile8": [
      0.984,
      0.782,
      1.008,
      0.726,
      0.993,
      0.81,
      1.057,
      0.795
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Hastinapur": {
    "profile8": [
      0.988,
      0.75,
      1.004,
      0.766,
      0.979,
      0.761,
      1.035,
      0.817
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#6ec8ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Map Celebration": {
    "profile8": [
      1.067,
      0.884,
      0.922,
      0.92,
      1.076,
      0.893,
      0.951,
      0.929
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aarohi Avinya": {
    "profile8": [
      1.031,
      0.749,
      0.975,
      0.773,
      1.04,
      0.778,
      1.024,
      0.842
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aarohi Galleria": {
    "profile8": [
      1.01,
      0.952,
      0.954,
      0.916,
      1.001,
      0.943,
      0.965,
      0.907
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aquavista": {
    "profile8": [
      1.05,
      0.912,
      0.906,
      0.948,
      1.041,
      0.903,
      0.997,
      0.939
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aleta": {
    "profile8": [
      1.047,
      0.729,
      1.091,
      0.773,
      1.038,
      0.72,
      1.082,
      0.765
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Trinay Anagh": {
    "profile8": [
      1,
      0.798,
      1.016,
      0.734,
      0.991,
      0.809,
      1.047,
      0.785
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#6ec8ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kiva 261": {
    "profile8": [
      0.991,
      0.786,
      1.004,
      0.722,
      0.979,
      0.797,
      1.035,
      0.853
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kameshwar Elite 140": {
    "profile8": [
      0.991,
      0.753,
      1.007,
      0.769,
      1,
      0.782,
      1.056,
      0.838
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Sujal Apartment": {
    "profile8": [
      0.962,
      0.805,
      0.978,
      0.74,
      0.971,
      0.833,
      1.027,
      0.809
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Saadhya 81": {
    "profile8": [
      1.061,
      0.957,
      0.926,
      0.924,
      1.05,
      0.948,
      0.934,
      0.912
    ],
    "bands": [
      1,
      0.86,
      0.74
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Shyaswa Sarovar": {
    "profile8": [
      0.993,
      0.79,
      1.008,
      0.726,
      0.984,
      0.802,
      1.039,
      0.857
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Shristi": {
    "profile8": [
      0.982,
      0.78,
      1.007,
      0.724,
      0.991,
      0.809,
      1.055,
      0.793
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Amaris": {
    "profile8": [
      1.014,
      0.776,
      0.949,
      0.792,
      1.005,
      0.787,
      0.98,
      0.843
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Samyak": {
    "profile8": [
      0.965,
      0.842,
      1.06,
      0.858,
      0.953,
      0.871,
      1.029,
      0.927
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Re 45 by Ratna": {
    "profile8": [
      1.001,
      0.763,
      0.945,
      0.788,
      1.01,
      0.792,
      0.994,
      0.856
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Elinor 51": {
    "profile8": [
      1.035,
      0.797,
      0.979,
      0.741,
      1.026,
      0.808,
      1.01,
      0.792
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Stark Torre": {
    "profile8": [
      0.97,
      0.812,
      0.985,
      0.748,
      0.961,
      0.823,
      1.017,
      0.799
    ],
    "bands": [
      1,
      0.68,
      0.38
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kalrav Trails by A.Shridhar": {
    "profile8": [
      1.005,
      0.847,
      1.03,
      0.872,
      0.994,
      0.876,
      0.998,
      0.861
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Kalrav Seasons by A.Shridhar": {
    "profile8": [
      1.058,
      0.956,
      0.913,
      0.911,
      1.067,
      0.884,
      0.942,
      0.92
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Emberlynn-2": {
    "profile8": [
      1.005,
      0.947,
      0.95,
      0.912,
      1.014,
      0.956,
      0.978,
      0.921
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#9aa7ff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Emberlynn-3": {
    "profile8": [
      1.08,
      0.798,
      1.044,
      0.762,
      1.071,
      0.789,
      1.036,
      0.753
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Aarohan By Emberlynn": {
    "profile8": [
      1.093,
      0.775,
      1.048,
      0.73,
      1.084,
      0.766,
      1.039,
      0.722
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#f2b880",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Emberlynn-1": {
    "profile8": [
      1.027,
      0.744,
      0.962,
      0.76,
      1.035,
      0.773,
      1.011,
      0.829
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#b58cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Shiv Vivanta": {
    "profile8": [
      1.012,
      0.774,
      0.948,
      0.79,
      1.003,
      0.785,
      1.059,
      0.841
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#7b8fff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Zade Two": {
    "profile8": [
      1.038,
      0.916,
      0.963,
      0.921,
      0.967,
      0.925,
      0.972,
      0.929
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#56cfdd",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Zade Stone": {
    "profile8": [
      0.975,
      0.898,
      1.08,
      0.842,
      0.947,
      0.909,
      1.031,
      0.893
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#4f6cff",
    "image": null,
    "source": "synthetic-fallback"
  },
  "Z North Face": {
    "profile8": [
      1.064,
      0.782,
      1.1,
      0.737,
      1.073,
      0.791,
      1.028,
      0.746
    ],
    "bands": [
      1,
      0.72,
      0.44
    ],
    "confidence": 0.22,
    "dominantColor": "#b58cff",
    "image": null,
    "source": "synthetic-fallback"
  }
}
;
